redis: &redis
  host: localhost
  port: 6379

development: &development
  namespace: carmakart
  <<: *redis
  cart:
    namespace: "carmakart:cart"
    <<: *redis

production:
  <<: *development
  namespace: "carmakart"

test:
  <<: *development
  namespace: "carmakart_test"
